### PR TITLE
SwiftPM, Xcode11 and iOS 13 support

### PR DESCRIPTION
**Pull request by yoiang**
Lemme know how it looks! 🖖

I'm sure you've given it some thought, property wrappers may save a ton of this boiler plate but more importantly be potentially a lot safer! In the midst of updating the tests I noticed a [mismatched case](https://github.com/vhesener/Closures/commit/dad3dfb8195da3b8aec086430ea6aa0a3c81751b#diff-1c0aeb6fa8ee7eedab6b9feb2b756047L407-L408), totally easy to do accidentally with such repetitive, dense code. Also means the tests might need to be elaborated on and test actual one to one calling.

### CODE REVIEW

**Comment by dusty-commits** [comment]
Ok I appreciate this. I need a little time to review but I have it in my queue.

**Comment by yoiang** [comment]
My pleasure, thanks so much for sharing the library!

**Comment by dusty-commits** [comment]
Can you please resubmit this to the develop branch instead of master?

**Comment by yoiang** [comment]
Sure!

**Pull request closed without merging**
